language: python
sudo: required
dist: bionic

python:
  - 3.8

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.8
    arch: arm64  # flakey
  include:
  - python: 3.8
    arch: arm64
  - python: 3.8
    arch: amd64
  - python: 3.8
    arch: arm64-graviton2
    dist: bionic
    group: edge
    virt: lxd
    sudo: true

git:
  depth: 9999

before_install:
  # temporary workaround for s390x and arm64 permissions problem
  # https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/12
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels || true

install:
  - pip install -r requirements.txt

script:
  - make test_coverage
after_success:
  coveralls
